### PR TITLE
Upgraded prometheus to newest version

### PR DESCRIPTION
**Pull request by Stephan3555**
Upgraded Prometheus to latest version.

Fixed unit tests as there is a new default metric called "_created". See: https://github.com/prometheus/client_java/releases/tag/parent-0.10.0

### CODE REVIEW

**Comment by Stephan3555** [comment]
@johrstrom would be nice if you could review my PR. I ugraded the prometheus client to newest version 0.16.0 and fixed the tests accordingly.

**Comment by hawk-stephan-stiefel** [comment]
@johrstrom any update? :-)

**Comment by Stephan3555** [comment]
@johrstrom any update? :-)

**Comment by johrstrom** [comment]
Sorry for the delay, I'll carve out some time tonight to sort this out.

**Comment by johrstrom** [comment]
Hey, I'm so sorry for the delay. I'll get this pushed out in a tag shortly.  I just had to rebase for you.  The tests changes through me off a bit so I had to look up the changes upstream.

Thanks for the contribution and again, sorry for the delay.

**Pull request merged**
