### PR TITLE
Add lazy initialization of registry and http server when used in distributed setup 

### PR DESCRIPTION
**Pull request by GiovanniPaoloGibilisco**
When running JMeter in a distributed way (multiple jmeter-server and one JMeter client) starting the test causes errors adding collectors to the registry and creating the Prometheus HTTP server. 
Tracing back the error the cause should be the way the plugin is initialized in server mode differs from the one in standalone mode and registers and HTTP server are not initialized. 

This pull request adds lazy initialization (if necessary) to both register and Prometheus server. 

Attached the generated Error. 

`2019-05-14 15:04:03,577 ERROR c.g.j.l.PrometheusListener: Didn't create new collector because of error, 
java.lang.NullPointerException: null
        at com.github.johrstrom.listener.PrometheusListener.makeNewCollectors(PrometheusListener.java:171) [jmeter-prometheus-plugin-0.5.0-SNAPSHOT.jar:?]
        at com.github.johrstrom.listener.PrometheusListener.testStarted(PrometheusListener.java:136) [jmeter-prometheus-plugin-0.5.0-SNAPSHOT.jar:?]
        at com.github.johrstrom.listener.PrometheusListener.testStarted(PrometheusListener.java:156) [jmeter-prometheus-plugin-0.5.0-SNAPSHOT.jar:?]
        at org.apache.jmeter.engine.StandardJMeterEngine.notifyTestListenersOfStart(StandardJMeterEngine.java:208) [ApacheJMeter_core.jar:5.1.1 r1855137]
        at org.apache.jmeter.engine.StandardJMeterEngine.run(StandardJMeterEngine.java:381) [ApacheJMeter_core.jar:5.1.1 r1855137]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
2019-05-14 15:04:03,580 ERROR c.g.j.l.PrometheusListener: Didn't create new collector because of error, 
java.lang.NullPointerException: null
        at com.github.johrstrom.listener.PrometheusListener.makeNewCollectors(PrometheusListener.java:171) [jmeter-prometheus-plugin-0.5.0-SNAPSHOT.jar:?]
        at com.github.johrstrom.listener.PrometheusListener.testStarted(PrometheusListener.java:136) [jmeter-prometheus-plugin-0.5.0-SNAPSHOT.jar:?]
        at com.github.johrstrom.listener.PrometheusListener.testStarted(PrometheusListener.java:156) [jmeter-prometheus-plugin-0.5.0-SNAPSHOT.jar:?]
        at org.apache.jmeter.engine.StandardJMeterEngine.notifyTestListenersOfStart(StandardJMeterEngine.java:208) [ApacheJMeter_core.jar:5.1.1 r1855137]
        at org.apache.jmeter.engine.StandardJMeterEngine.run(StandardJMeterEngine.java:381) [ApacheJMeter_core.jar:5.1.1 r1855137]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
2019-05-14 15:04:03,581 ERROR c.g.j.l.PrometheusListener: Didn't create new collector because of error, 
java.lang.NullPointerException: null
        at com.github.johrstrom.listener.PrometheusListener.makeNewCollectors(PrometheusListener.java:171) [jmeter-prometheus-plugin-0.5.0-SNAPSHOT.jar:?]
        at com.github.johrstrom.listener.PrometheusListener.testStarted(PrometheusListener.java:136) [jmeter-prometheus-plugin-0.5.0-SNAPSHOT.jar:?]
        at com.github.johrstrom.listener.PrometheusListener.testStarted(PrometheusListener.java:156) [jmeter-prometheus-plugin-0.5.0-SNAPSHOT.jar:?]
        at org.apache.jmeter.engine.StandardJMeterEngine.notifyTestListenersOfStart(StandardJMeterEngine.java:208) [ApacheJMeter_core.jar:5.1.1 r1855137]
        at org.apache.jmeter.engine.StandardJMeterEngine.run(StandardJMeterEngine.java:381) [ApacheJMeter_core.jar:5.1.1 r1855137]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
2019-05-14 15:04:03,581 ERROR c.g.j.l.PrometheusListener: Didn't create new collector because of error, 
java.lang.NullPointerException: null
        at com.github.johrstrom.listener.PrometheusListener.makeNewCollectors(PrometheusListener.java:171) [jmeter-prometheus-plugin-0.5.0-SNAPSHOT.jar:?]
        at com.github.johrstrom.listener.PrometheusListener.testStarted(PrometheusListener.java:136) [jmeter-prometheus-plugin-0.5.0-SNAPSHOT.jar:?]
        at com.github.johrstrom.listener.PrometheusListener.testStarted(PrometheusListener.java:156) [jmeter-prometheus-plugin-0.5.0-SNAPSHOT.jar:?]
        at org.apache.jmeter.engine.StandardJMeterEngine.notifyTestListenersOfStart(StandardJMeterEngine.java:208) [ApacheJMeter_core.jar:5.1.1 r1855137]
        at org.apache.jmeter.engine.StandardJMeterEngine.run(StandardJMeterEngine.java:381) [ApacheJMeter_core.jar:5.1.1 r1855137]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
2019-05-14 15:04:03,581 ERROR c.g.j.l.PrometheusListener: Didn't create new collector because of error, 
java.lang.NullPointerException: null
        at com.github.johrstrom.listener.PrometheusListener.makeNewCollectors(PrometheusListener.java:171) [jmeter-prometheus-plugin-0.5.0-SNAPSHOT.jar:?]
        at com.github.johrstrom.listener.PrometheusListener.testStarted(PrometheusListener.java:136) [jmeter-prometheus-plugin-0.5.0-SNAPSHOT.jar:?]
        at com.github.johrstrom.listener.PrometheusListener.testStarted(PrometheusListener.java:156) [jmeter-prometheus-plugin-0.5.0-SNAPSHOT.jar:?]
        at org.apache.jmeter.engine.StandardJMeterEngine.notifyTestListenersOfStart(StandardJMeterEngine.java:208) [ApacheJMeter_core.jar:5.1.1 r1855137]
        at org.apache.jmeter.engine.StandardJMeterEngine.run(StandardJMeterEngine.java:381) [ApacheJMeter_core.jar:5.1.1 r1855137]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
2019-05-14 15:04:03,582 ERROR c.g.j.l.PrometheusListener: Didn't create new collector because of error, 
java.lang.NullPointerException: null
        at com.github.johrstrom.listener.PrometheusListener.makeNewCollectors(PrometheusListener.java:171) [jmeter-prometheus-plugin-0.5.0-SNAPSHOT.jar:?]
        at com.github.johrstrom.listener.PrometheusListener.testStarted(PrometheusListener.java:136) [jmeter-prometheus-plugin-0.5.0-SNAPSHOT.jar:?]
        at com.github.johrstrom.listener.PrometheusListener.testStarted(PrometheusListener.java:156) [jmeter-prometheus-plugin-0.5.0-SNAPSHOT.jar:?]
        at org.apache.jmeter.engine.StandardJMeterEngine.notifyTestListenersOfStart(StandardJMeterEngine.java:208) [ApacheJMeter_core.jar:5.1.1 r1855137]
        at org.apache.jmeter.engine.StandardJMeterEngine.run(StandardJMeterEngine.java:381) [ApacheJMeter_core.jar:5.1.1 r1855137]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
2019-05-14 15:04:03,582 ERROR c.g.j.l.PrometheusListener: Didn't create new collector because of error, 
java.lang.NullPointerException: null
        at com.github.johrstrom.listener.PrometheusListener.makeNewCollectors(PrometheusListener.java:171) [jmeter-prometheus-plugin-0.5.0-SNAPSHOT.jar:?]
        at com.github.johrstrom.listener.PrometheusListener.testStarted(PrometheusListener.java:136) [jmeter-prometheus-plugin-0.5.0-SNAPSHOT.jar:?]
        at com.github.johrstrom.listener.PrometheusListener.testStarted(PrometheusListener.java:156) [jmeter-prometheus-plugin-0.5.0-SNAPSHOT.jar:?]
        at org.apache.jmeter.engine.StandardJMeterEngine.notifyTestListenersOfStart(StandardJMeterEngine.java:208) [ApacheJMeter_core.jar:5.1.1 r1855137]
        at org.apache.jmeter.engine.StandardJMeterEngine.run(StandardJMeterEngine.java:381) [ApacheJMeter_core.jar:5.1.1 r1855137]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
2019-05-14 15:04:03,582 ERROR c.g.j.l.PrometheusListener: Didn't create new collector because of error, 
java.lang.NullPointerException: null
        at com.github.johrstrom.listener.PrometheusListener.makeNewCollectors(PrometheusListener.java:171) [jmeter-prometheus-plugin-0.5.0-SNAPSHOT.jar:?]
        at com.github.johrstrom.listener.PrometheusListener.testStarted(PrometheusListener.java:136) [jmeter-prometheus-plugin-0.5.0-SNAPSHOT.jar:?]
        at com.github.johrstrom.listener.PrometheusListener.testStarted(PrometheusListener.java:156) [jmeter-prometheus-plugin-0.5.0-SNAPSHOT.jar:?]
        at org.apache.jmeter.engine.StandardJMeterEngine.notifyTestListenersOfStart(StandardJMeterEngine.java:208) [ApacheJMeter_core.jar:5.1.1 r1855137]
        at org.apache.jmeter.engine.StandardJMeterEngine.run(StandardJMeterEngine.java:381) [ApacheJMeter_core.jar:5.1.1 r1855137]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
`

### CODE REVIEW

**Comment by johrstrom** [comment]
Giovanni, thanks the the PR!!! I am currently traveling so I can't look at it until the weekend.

Is there any way to get a test case for this?  You can see I have a very simple one for stopping and starting cleanly, but I guess I misses initializing some collectors.


-------- Original message --------

**Comment by GiovanniPaoloGibilisco** [comment]
I was not able to reproduce the same initialization procedure performed by Jmeter in server mode so I had to reproduce the effects. 
Setting null both registry and server when testStarted function is called.

**Comment by johrstrom** [comment]
Sorry this has taken so long. I just moved and started a new job over the past 2 months.

Looking over the code, it's hard to tell what all has changed by the diff. Your ide must have reformatted and changed almost every line of code.

I'll be sure to look into it more in depth this weekend.

**Comment by GiovanniPaoloGibilisco** [comment]
I merged the content of the other pull request here, it's not nice but it was needed to get a version with both of them (should have probably been done locally only)

**Comment by johrstrom** [comment]
I'm sorry I never got around to this.  We have a discussion about the other feature in the other PR.  I think you should reset those commits in this PR. 

The diff is too big for me to see what actually changed.  I'm going to need to pull it and reset it to my editor settings I guess and then I can see the actual diff. 

That said, I think the core feature is good and tests added, so this shouldn't such a big thing to pull in, I just need to be able to get a good sense of what the actual diff is.

**Comment by providentiaww** [comment]
Works well for me on large distributed tests (48 worker nodes -- all being scraped by prometheus successfully). Thanks for this -- solved a lot of issues for me.

**Comment by johrstrom** [comment]
Hey, thanks again for the PR. I formatted some things a little bit (we use tabs in this family), but save for that everything is OK.  

Your IDE must change the order of imports, which just sucks for a PR because it's a bunch of meaningless changes. Or you changed the order, either way I'm fine with that. I saw all the changes to the tests too, which are optimizations in readability for sure. 

In any case, I'm closing this PR in favor of #60 which is only the server initialization feature with some formatting updates by me. 

We can talk about the features in 57 in that PR.

**Pull request closed without merging**
