### PR TITLE
Feature/expose percentile window lenght

### PR DESCRIPTION
**Pull request by GiovanniPaoloGibilisco**
Allows specifying the length of the time window used to calculate the percentile aggregation on summary collectors. The default value of 10 minutes (which still remains the default) is a bit too long for some use cases.

### CODE REVIEW

**Comment by johrstrom** [comment]
You'll need to merge with master to get the tests to pass, I had to update surefire for higher versions of java.

That said, shouldn't this just be a global property you set in `user.properties`? I don't know if I like adding another column. Yes, this means you can set a time for every individual metric, but do users need that level of granularity or does a global parameter work?

Obviously you needed this so you added it, would a global config have worked for you?

**Comment by GiovanniPaoloGibilisco** [comment]
I found my self in a couple of situations where I needed different aggregating at different time ranges for different requests so I would leave the possibility to do that. 
I agree that adding another column at the table (which is not used when another type of collector is used) is not ideal. Probably the overall way of visualizing this configuration data as a table could be improved.

**Comment by johrstrom** [comment]
> Visualizing this configuration data as a table could be improved.

I'm open to suggestions!

As to our current problem, how about this as a potential solution, you can override the windows in a bar separated variable name comma override value property list. That way it's not global 1 property you override the variables you want. 

Something like this:
`prometheus.listener.window_overrides=first_var,30|second_var,7`

**Comment by GiovanniPaoloGibilisco** [comment]
Closed as addressed by #74

**Pull request closed without merging**
